version: 2
jobs:
    build:
        working_directory: ~/wapplate/client
        docker:
            - image: circleci/node:10-browsers
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Change directory
            - run:
                name: Client directory
                command: cd client
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
            # Build project
            - run: 
                name: Building
                command: npm build
